# Generated by Django 4.1.1 on 2022-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilitybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water')], max_length=20, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
