# Generated by Django 4.1.1 on 2022-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salasry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20, null=True)),
                ('basicSal', models.FloatField(null=True)),
                ('OT_houres', models.PositiveIntegerField(null=True)),
                ('OT_Rate', models.FloatField(null=True)),
                ('total_sal', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='bill_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
