# Generated by Django 4.1.1 on 2022-09-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0002_employee_salasry_utilitybill_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_salasry',
            name='deduction_sal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employee_salasry',
            name='increment_sal',
            field=models.FloatField(null=True),
        ),
    ]
