# Generated by Django 4.1.1 on 2022-09-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0003_employee_salasry_deduction_sal_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee_salasry',
            table='employee_salasry',
        ),
        migrations.AlterModelTable(
            name='utilitybill',
            table='utilitybill',
        ),
    ]
