# Generated by Django 4.1.1 on 2022-09-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0004_alter_employee_salasry_table_alter_utilitybill_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee_salasry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='utilitybill',
            table=None,
        ),
    ]
