# Generated by Django 4.1.1 on 2022-09-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0005_alter_employee_salasry_table_alter_utilitybill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_salasry',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
