# Generated by Django 4.1.1 on 2022-09-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0007_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='fashion_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierId', models.PositiveIntegerField(null=True)),
                ('ordermngrId', models.PositiveIntegerField(null=True)),
                ('quantity_order', models.PositiveIntegerField(null=True)),
                ('orderDate', models.DateField(max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('ordermngrName', models.CharField(max_length=50, null=True)),
                ('supplieName', models.CharField(max_length=50, null=True)),
                ('item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardnew.item')),
            ],
        ),
    ]
