# Generated by Django 4.1.1 on 2022-09-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0008_fashion_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50, null=True)),
                ('Size', models.CharField(max_length=50, null=True)),
                ('Price', models.FloatField(null=True)),
                ('QTY', models.PositiveIntegerField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('Item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardnew.item')),
            ],
        ),
    ]
