# Generated by Django 4.1.1 on 2022-09-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardnew', '0011_rename_basicsal_employee_salasry_basic_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_salasry',
            old_name='deduction_sal',
            new_name='deduction',
        ),
        migrations.RenameField(
            model_name='employee_salasry',
            old_name='increment_sal',
            new_name='increment',
        ),
    ]
